spring:
  datasource:
    name: test
    url: jdbc:postgresql://127.0.0.1:5432/bfp20180723_db?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: Abc12345
    #配置druid作为数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      maxActive: 50
      filters: stat
      initialSize: 1
      maxWait: 5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 60000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false